speakapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from . import views 


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'), 
    url(r'^list', views.list, name='list'),
    url(r'^campaing/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^add', views.add, name='add'),
    url(r'^agree', views.agree, name='agree'),
    url(r'^disagree', views.disagree, name='disagree'),
    url(r'^parseJson', views.parseJson, name='parseJson'),    
    #url(r'^auth', views.twitterAuthenticate),
    url(r'^register/', include('twitter_registration.urls', namespace="twitter_registration")),    
]

twitter_registration/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	#url(r'^$', views.index, name='index'),
    url(r'^auth', views.twitterAuthenticate, name="auth"),
    url(r'^callback/', views.twitterAuthorizeCallback),    
    url(r'^logout', views.user_logout),
]

speakapp/models.py
from django.db import models
from django import forms
from django.core.validators import RegexValidator
from django.contrib.auth.models import User

class Category(models.Model):
	name = models.CharField(max_length=100, null=False, blank=False)
	
	def __str__(self):
		return self.name

class Location(models.Model):
	name = models.CharField(max_length=200,null=False, blank=False)
	parent = models.OneToOneField('self', null=True, blank=True)
	
	def __str__(self):
		return self.name

class Post(models.Model):
	message 	= models.TextField(null=False, blank=False)
	author 		= models.ForeignKey(User)
	category 	= models.ForeignKey(Category, null=False, blank=False)
	location 	= models.ForeignKey(Location, null=False, blank=False)	
	backers 	= models.ManyToManyField(User, related_name="backers",null=True, blank=True)
	opposers 	= models.ManyToManyField(User, related_name="opposers", null=True, blank=True)
	twitter_accounts = models.CharField(max_length=200)	
	
	def __str__(self):
		return self.message

twitter_registration/models.py
from django.db import models
from django import forms
from django.core.validators import RegexValidator
from django.contrib.auth.models import User

class TwitterUser(models.Model):
	user = models.OneToOneField(User, related_name='twitter_user')
	twitter_id = models.BigIntegerField()
	access_token = models.CharField(max_length=200)
	access_token_secret = models.CharField(max_length=200)
	

twitter_registration/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import logout, login, authenticate
import tweepy
from .models import TwitterUser
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.conf import settings
from twitter_registration.settings import *
from django.core import serializers

def twitterAuthenticate(request):
    auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET, CALLBACK_URL)

    try:
        redirect_url = auth.get_authorization_url()
    except tweepy.TweepError as e:        
        return HttpResponse('error', status=500)

    request.session['request_token'] = (auth.request_token)
    
    return HttpResponseRedirect(redirect_url)

def twitterAuthorizeCallback(request):
    verifier = request.GET.get('oauth_verifier')

    auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)

    token = request.session.get('request_token')
    request.session.delete('request_token')
    auth.request_token = token

    try:
        auth.get_access_token(verifier)
    except tweepy.TweepError:
        return HttpResponse('error', status=500)
    

    response_data = {}
    response_data = auth.access_token    
        
    
    api = tweepy.API(auth)
    #data = api.me()
    data = api.verify_credentials(include_email = "true")

    data = {'id' : data.id,
            'username' : data.screen_name,
            'email' : data.email,
            'name': data.name,
            'access_token' : auth.access_token,
            'access_token_secret' : auth.access_token_secret,}
    
    user = userExist(data["id"])
    if(user):
        user_login(request,user.user)
        mensaje="login"
    else:
        mensaje="register"
        user = registerTwitter(data)
        user_login(request,user.user)
    #api.update_status(status='tweepy + oauth!2') #The status must change on each execution

    return redirect('speakapp.views.list')
    #return HttpResponse("mensaje")

def userExist(twitterId):      
    user = False
    try:
        user = TwitterUser.objects.get(twitter_id=twitterId)
    except:
        exist = False
    return user

def registerTwitter(data):
    newUser = TwitterUser()
    baseUser = User.objects.create_user(
            username = data["username"],
            password = data["username"] + PASSWORD_SALT,
            email = data["email"],            
            )
    newUser.user = baseUser
    newUser.twitter_id = data["id"]
    newUser.access_token = data["access_token"]
    newUser.access_token_secret = data["access_token_secret"]
    newUser.save()

    return newUser

def user_login(request, twitteruser):
    # Use Django's machinery to attempt to see if the username/password
    # combination is valid - a User object is returned if it is.
    user = authenticate(username=twitteruser.username, password=twitteruser.username + PASSWORD_SALT)

    # If we have a User object, the details are correct.
    # If None (Python's way of representing the absence of a value), no user
    # with matching credentials was found.
    if user:
        # Is the account active? It could have been disabled.
        if user.is_active:        
            # If the account is valid and active, we can log the user in.
            # We'll send the user back to the homepage.
            login(request, user)
            return HttpResponseRedirect('/rango/')
        else:
            # An inactive account was used - no logging in!
            return HttpResponse("Your Rango account is disabled.")
    else:
        # Bad login details were provided. So we can't log the user in.
        #print "Invalid login details: {0}, {1}".format(username, password)
        return HttpResponse("Invalid login details supplied.")


def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')
    #return HttpResponse("logged out")

def update_status(user, message):
    try:
        auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)    
        auth.set_access_token(user.access_token, user.access_token_secret)
        api = tweepy.API(auth)
        api.update_status(status=message)    
    except:
        return False;

speakapp/templates/speakapp/add.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>SpeakApp</title>

    <!-- Bootstrap core CSS -->
    <link href="static/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="static/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="static/css/theme.css" rel="stylesheet">    

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body role="document">

    <!-- Fixed navbar -->
    <nav id="menu-top" class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="row">
          <a class="navbar-brand col-xs-6" href="./">SpeakApp</a>
          <a class="col-xs-6" id="add-button" href="./add.html">
             <span class="pull-right glyphicon glyphicon-plus" aria-hidden="true"></span>
          </a>          
        </div>
        
      </div>
    </nav>

    <div class="container main-container" role="main">

   
      <div class="card">
        <div id="new-topic">
          <h4>Nueva Campaña</h4>
          <hr>
          <form id="add-post" method="POST" action="./add">
            {% csrf_token %} 
            <div class="row">
              <div class="col-xs-12">
                <div class="input">                  
                  <select id="category_id" name="category_id" class="form-control">  
                    <option disabled selected>Elige un tema: </option>
                   {% for category in categories %}
                      <option value="{{category.id}}">{{category.name}}</option>
                   {% endfor %}               
                  </select>
                </div>
                <div class="input">                  
                  <input id="location" type="text" class="form-control typeahead" autocomplete="off" placeholder="Lugar: Bogotá, Antioquia">
                  <input type="hidden" name="location_id" class="form-control">
                </div>
                <div class="input">                  
                  <input id="twitter-accounts" type="text" name="twitter_accounts" class="form-control" placeholder="Hashtag: #Colombia #MedellinElige">
                </div>
              </div>
          </div>
             <div class="row">
                <div class="col-xs-12">                  
                  <textarea id="text" name="message" placeholder="Escribe un texto que acompañe al Hashtag de la campaña y a partir del cual otros puedan apoyarte"></textarea>
                  <p id="text-counter"><span id="variable">0</span> / <span id="max-length">{{post_max_length}}</span></p>
                </div>
             </div>
             <div class="row">
                <div class="col-xs-12">
                  <button class="button ok pull-right">Enviar</button>
                  <button class="button cancel pull-right">Cancelar</button>               
                  
               </div>
             </div>
           </form>
          </div>
        </div>
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="static/js/bootstrap.min.js"></script>
    <script src="static/js/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="static/js/ie10-viewport-bug-workaround.js"></script>
    <script src="static/js/typeahead.bundle.js"></script>
    <script type="text/javascript">
    $(document).ready(function(){
        var data = [];
        var maxLength = {{post_max_length}};
        var locations = [];
        var map = {};
        length = maxLength;      

        $("#text").on('change keyup paste', function(){
          if($(this).val().length >= length){
            $(this).val($(this).val().substring(0,length));
          }
          $("#variable").html($(this).val().length);
        });

        $("#twitter-accounts").on('change keyup paste', function(){
            length = maxLength - $(this).val().length;
            $("#max-length").html(length);
            $("#text").trigger("change");
        });


        {% for location in locations %}
            data.push({"name":"{{location.name}}", "id" : {{location.id}} });
        {% endfor %}                 
        $('#location').typeahead({
          source : function(query, process){
            locations = [];
            map = {};
         
            $.each(data, function (i, location) {
                map[location.name] = location;
                locations.push(location.name);
            });
         
            process(locations);
          },
          updater: function (item) {              
              $('input[name=location_id]').val(map[item].id);
              return item;
          }
        });

        $(".button.ok").click(function(){
            var r = confirm("¿Seguro que quieres publicar tu mensaje ahora?");
            if (r == true) {
                txt = "Si!";
                $("#add-post").submit();
            } else {
                txt = "No";
                return false;
            }
        });

        $(".button.cancel").click(function(){
            var r = confirm("Perderás los cambios realizados ¿Salir ahora?");
            if (r == true) {
                txt = "Si!";
                window.location.href = "/";                
            } else {
                txt = "No";                
            }
            return false;
        });
           
    });  
    </script>
  </body>
</html>

speakapp/templates/speakapp/detail.html
{% load post_extras %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>SpeakApp</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/static/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/theme.css" rel="stylesheet">    
    <link href="/static/css/jquery.sidr.light.css" rel="stylesheet">          

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body role="document">
    <div id="sidr">
      <!-- Your content -->
      <ul>
        {% for category in categories %}
          <li><a href="/list?category_id={{category.id}}">{{category.name}}</a></li>  
        {% endfor %}              
          <li id="logout"><a href="/register/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
      </ul>
    </div>
    <div class="sidr-overlay" style="display: none;"></div>
    <!-- Fixed navbar -->
    <nav id="menu-top" class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="row">          
          <div class="col-xs-6">
            <a href="#sidr" id="sidr-button"><span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span></a>
            <a class="navbar-brand" href="./">SpeakApp</a>
          </div>
          <div class="col-xs-6">
            <a id="add-button" class="pull-right" href="/add">
               <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </a>          
          </div>
        </div>
        
      </div>
    </nav>

    <div class="container main-container" role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <!--<div class="card">
        <h1>Welcome to SpeakApp!</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed dui porttitor nibh malesuada vestibulum. In venenatis felis a pharetra ultrices. Aenean ornare sed nunc sed vulputate. Duis imperdiet mollis tellus. Vestibulum scelerisque purus ut sapien accumsan, eu varius dui iaculis. Praesent sed ipsum rhoncus.</p>
      </div>-->
      {% if posts %}
        {% for post in posts %}                                     
        <div class="card">
            {% if post.id|is_backer:current_user.id %}
              <div class="topic is-backer" is-backer="1">            
            {% elif post.id|is_opposer:current_user.id %}
              <div class="topic is-opposer" is-backer="0">
            {% else %}
              <div class="topic">
            {% endif %}           
            <div class="category"><span class="glyphicon glyphicon-star"></span>{{post.category.name}}</div>
            <div class="text">
              {{post.message}}
            </div>                      
                                                      
            <div class="actions">
              
                {% if not post.id|is_backer:current_user.id and not post.id|is_opposer:current_user.id %}
                <form action="/agree" method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="post_id" value="{{post.id}}">
                  <button class="agree">APOYAR</button>
                </form>
                <form action="/disagree" method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="post_id" value="{{post.id}}">
                  <button class="disagree">NO APOYAR</button>
                </form>        
                {% elif not user_is_anonymous %} 
                <div class="piechart-container row vertical-align">
                  <div class="backers count col-xs-4 "><span class="text">Apoya</span><span class="percentage">{{ post.num_backers|percentage_backers:post.num_opposers }}%</span></div>
                  <div class="col-xs-4 no-padding">
                    <div id="piechart-{{post.id}}" class="piechart" style="max-width: 300px; margin: 0 auto" data-highcharts-chart="0" data-yes="{{post.num_backers}}" data-no="{{post.num_opposers}}"></div>
                  </div>
                  <div class="opposers count col-xs-4 "><span class="text">No Apoya</span><span class="percentage">{{ post.num_opposers|percentage_backers:post.num_backers }}%</span></div>
                </div>
                {% else %}
                  <p>Registrate y apoya esta campaña ahora!</p>
                {% endif %}                
            </div>
                
            
          </div>
        </div>
        {% endfor %}    
      {% else %}
        <p id="empty">No se encontraron resultados!</p>
      {% endif %}    
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/docs.min.js"></script>
    <script src="/static/js/jquery.sidr.min.js"></script>     
    <script src="/static/js/scripts.js"></script> 
    <script src="/static/js/highcharts.js"></script>    
    <script src="/static/js/exporting.js"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/js/ie10-viewport-bug-workaround.js"></script>        
  </body>
</html>

speakapp/templates/speakapp/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Theme Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="static/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="static/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="static/css/theme.css" rel="stylesheet">    

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body id="login-body" role="document">
    <div class="container">
      <div id="login-container" class="col-xs-12">
        <h1>SpeakApp</h1>
        <h5>BETA</h5>
        <a id="login-button" href="{% url 'twitter_registration:auth' %}"><img src="./static/twitter.png"/></a>        
        <p>Lorem ipsum dolor amet. Sherp mas divulg mareq. <a href="#">aqui pdoe</a>.</p>
      </div>
      </div>


    


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="static/js/bootstrap.min.js"></script>
    <script src="static/js/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="static/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

speakapp/templates/speakapp/list.html
{% load post_extras %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>SpeakApp</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/static/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/theme.css" rel="stylesheet">    
    <link href="/static/css/jquery.sidr.light.css" rel="stylesheet">          

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body role="document">
    <div id="sidr">
      <!-- Your content -->
      <ul>
        {% for category in categories %}
          <li><a href="/list?category_id={{category.id}}">{{category.name}}</a></li>  
        {% endfor %}              
          <li id="logout"><a href="/register/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
      </ul>
    </div>
    <div class="sidr-overlay" style="display: none;"></div>
    <!-- Fixed navbar -->
    <nav id="menu-top" class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="row">          
          <div class="col-xs-6">
            <a href="#sidr" id="sidr-button"><span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span></a>
            <a class="navbar-brand" href="./">SpeakApp</a>
          </div>
          <div class="col-xs-6">
            <a id="add-button" class="pull-right" href="/add">
               <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </a>          
          </div>
        </div>
        
      </div>
    </nav>

    <div class="container main-container" role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <!--<div class="card">
        <h1>Welcome to SpeakApp!</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed dui porttitor nibh malesuada vestibulum. In venenatis felis a pharetra ultrices. Aenean ornare sed nunc sed vulputate. Duis imperdiet mollis tellus. Vestibulum scelerisque purus ut sapien accumsan, eu varius dui iaculis. Praesent sed ipsum rhoncus.</p>
      </div>-->
      {% if posts %}
        {% for post in posts %}                                     
        <div class="card">
            {% if post.id|is_backer:current_user.id %}
              <div class="topic is-backer" is-backer="1">            
            {% elif post.id|is_opposer:current_user.id %}
              <div class="topic is-opposer" is-backer="0">
            {% else %}
              <div class="topic">
            {% endif %}           
            <div class="category"><span class="glyphicon glyphicon-star"></span>{{post.category.name}}</div>
            <div class="hashtag">
              <span>#</span>{{ post.twitter_accounts|clean_hashtag }}
            </div>
            <div class="text">
              {{post.message}}
            </div>                      
                                                      
            <div class="actions">
              
                {% if not post.id|is_backer:current_user.id and not post.id|is_opposer:current_user.id %}
                <form action="/agree" method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="post_id" value="{{post.id}}">
                  <button class="agree">APOYAR</button>
                </form>
                <form action="/disagree" method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="post_id" value="{{post.id}}">
                  <button class="disagree">NO APOYAR</button>
                </form>        
                {% else %} 
                <div class="piechart-container row vertical-align">
                  <div class="backers count col-xs-4 "><span class="text">Apoya</span><span class="percentage">{{ post.num_backers|percentage_backers:post.num_opposers }}%</span></div>
                  <div class="col-xs-4 no-padding">
                    <div id="piechart-{{post.id}}" class="piechart" style="max-width: 300px; margin: 0 auto" data-highcharts-chart="0" data-yes="{{post.num_backers}}" data-no="{{post.num_opposers}}"></div>
                  </div>
                  <div class="opposers count col-xs-4 "><span class="text">No Apoya</span><span class="percentage">{{ post.num_opposers|percentage_backers:post.num_backers }}%</span></div>
                </div>
                {% endif %}                
            </div>
                
            
          </div>
        </div>
        {% endfor %}    
      {% else %}
        <p id="empty">No se encontraron resultados!</p>
      {% endif %}    
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/docs.min.js"></script>
    <script src="/static/js/jquery.sidr.min.js"></script>     
    <script src="/static/js/scripts.js"></script> 
    <script src="/static/js/highcharts.js"></script>    
    <script src="/static/js/exporting.js"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/js/ie10-viewport-bug-workaround.js"></script>        
  </body>
</html>

speakapp/templates/speakapp/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Theme Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="theme.css" rel="stylesheet">    

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body id="login-body" role="document">
    <div class="container">
      <div id="login-container" class="col-xs-12">
        <h1>SpeakApp</h1>
        <h5>BETA</h5>

        <a id="login-button" href="./list.html"><img src="./img/twitter-login.png"></a>
        <p>Lorem ipsum dolor amet. Sherp mas divulg mareq. <a href="#">aqui pdoe</a>.</p>
      </div>
      </div>


    


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="../../assets/js/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>